### ISSUE TITLE
Add support of readonly and final tags for classes

### ISSUE THREAD

**Issue by staromand** [typhoon-php/reflection#19]
As you said on the last stream

**Comment by staromand** [comment]
https://github.com/typhoon-php/reflection/pull/20

Having nothing better to do, I played with your reflector code, learning it
Decided to do a little useful, who knows?

**Comment by vudaltsov** [comment]
Thank you for the issue! I am already working on this for 0.3.x, see https://github.com/typhoon-php/reflection/pull/20#issuecomment-1741727144
