### ISSUE TITLE
Support parameter attributes inside function brackets

### ISSUE THREAD

**Issue by roxblnfk** [typhoon-php/reflection#21]
Add support for parameters annotations inside the `()` function brackets.
It isn't good practice but it works with psalm and phpstorm.

![image](https://github.com/typhoon-php/reflection/assets/4152481/d489a754-5b08-4c87-8480-2761fb4a0ec1)

**Comment by vudaltsov** [comment]
Thank you for the issue! Added `@var` support for promoted properties in 0.3.0.
